main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Content
    url: /content/
    weight: 3
  - name: Assignments
    url: /assignments/
    weight: 4
  - name: Resources
    url: /resource/
    weight: 7
  - name: '<i class="fab fa-slack"></i>'
    url: "https://gsudatavizm2020.slack.com"
    weight: 8

content:
  - name: Overview
    weight: 1
  - name: Course content
    weight: 2
assignments:
  - name: Overview
    weight: 1
  - name: Projects
    weight: 2
  - name: Exercises
    weight: 3
