# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Syllabus"
  url = "syllabus"
  weight = 10

[[main]]
  name = "Schedule"
  url = "schedule"
  weight = 20

[[main]]
  name = "Content"
  url = "content"
  weight = 30
  
[[main]]
  name = "Assignments"
  url = "assignment"
  weight = 40

[[main]]
  name = "Resources"
  url = "resource"
  weight = 50
  
[[main]]
  name = '<i class="fab fa-r-project"></i>'
  url = "https://www.r-project.org"
  weight = 60
  
[[main]]
  name = '<i class="fab fa-slack"></i>'
  url = "https://posc-6013.slack.com"
  weight = 70
  
[[main]]
  name = 'Stata'
  url = "https://stata.com"
  weight = 80


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
