theme = "plasma"
day_night = false
font = "fira"
font_size = "L"
site_type = "Course"
description = "Communicate science and statistics with beautiful graphics made with R and ggplot2"
logo = ""
highlight = true
highlight_languages = [
  "r"
]
math = true
diagram = false
privacy_pack = false
author = "Andrew Heiss"
sharing_image = "social-image.png"
twitter = "andrewheiss"
date_format = "January 2, 2006"
time_format = "3:04 PM"
gravatar = false
reading_time = false
section_pager = false
docs_section_pager = false
sharing = false
link_authors = false
plugins_js = []

[edit_page]
repo_url = "https://github.com/andrewheiss/datavizm20.classes.andrewheiss.com"
content_dir = ""
repo_branch = "master"

  [edit_page.editable]
  docs = true
  page = false
  post = false

[instructor]
name = "Dr. Andrew Heiss"
email = "aheiss@gsu.edu"
url = "https://www.andrewheiss.com"
twitter = "andrewheiss"
github = "andrewheiss"
office = "357 Andrew Young School"
contact_policy = "E-mail and Slack are the best ways to get in contact with me. I will try to respond to all course-related e-mails and Slack messages within 24 hours (*really*), but also remember that life can be busy and chaotic for everyone (including me!), so if I don't respond right away, don't worry!"
appointment_url = "https://calendly.com/andrewheiss/meeting/"

[course]
number = "PMAP 8921"
semester = "Maymester 2020"
days = "Every day"
time = "Whenever"
dates = "May 11–June 1, 2020"
github = "andrewheiss/datavizm20.classes.andrewheiss.com"
copyrightYear = "2020"
slack = "https://gsudatavizm2020.slack.com"

[university]
name = "Georgia State University"
url = "https://www.gsu.edu"

[school]
name = "Andrew Young School of Policy Studies"
url = "https://aysps.gsu.edu/"

[main_menu]
align = "r"
show_logo = true

[comments]
engine = 0.0

  [comments.commentable]
  page = true
  post = true
  docs = true
  project = true
  publication = true
  talk = true

  [comments.disqus]
  shortname = ""
  show_count = true

  [comments.commento]
  url = ""

[search]
engine = 0.0

  [search.algolia]
  app_id = ""
  api_key = ""
  index_name = ""
  show_logo = false

[marketing]
google_analytics = ""
google_tag_manager = ""