---
title: Syllabus
slug: syllabus
output:
  blogdown::html_page:
    toc: false
    fig_caption: false
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```


# Course Description

This course focuses on the: *Quantitative analysis of political phenomena, including research design and analysis, theory formation, hypotheses, analytical techniques, and advanced regression.* This is accomplished by building on the foundational materials presented in POSC 6003 to expand our understanding of generalized linear models, interpretation, and applied econometrics. A familiarity with basic mathematical principles, linear algebra, and elementary calculus are helpful but not required. Elementary programming skills are also useful but not required. All efforts will be made to ensure course materials are accessible and presented in as basic terms as possible. If at any time a student is struggling to grasp the concepts for a given topic, please contact Dr. Wimpy immediately. 


# Course Learning Objectives

1. Develop the ability to implement the social scientific process of theory building and testing. 

2. Develop the ability to propose and understand graduate-level research design and implementation.

3. Develop knowledge of advanced statistical tools, such linear regression, sampling, surveys, and hypothesis tests.

4.  Develop acumen in probability theory, such as conditional probability, the law of averages, expected values, and estimates of uncertainty.

5. Develop the ability to evaluate empirical arguments, use `Stata` to implement basic statistical tools, and clearly explain data and analysis in an honest and compelling manner.

6. Develop the ability to apply substance to practice through effective research communication and dissemination. 

# Outcomes 

Your development will be demonstrated by your ability to:

1. Evaluate econometric and statistical problems using `Stata`.
2. Identify appropriate techniques and functions for evaluating advanced quantitative research problems. 
3. Apply advanced problem-solving and data analysis skills to theoretical problems from the literature.

**Assessment of Learning Outcomes:** Assessment will consist of weekly assignments and two exams (see assignments and grading policies below). 

# Course Requirements

## Textbooks

This textbook is required. You can search for it online, in the bookstore, and view the publishers website via this ISBN: [978-0262232586](https://mitpress.mit.edu/books/econometric-analysis-cross-section-and-panel-data-second-edition). You may consider an earlier edition, but do not expect me to translate any differences between the versions. 

## Software

This course require the use of the [`Stata`](https://www.stata.com). You can purchase the software if you wish or use the pre-installed versions in the computer labs. In either case, you must have access to a computer that can run `Stata`.  You can get started learning in `Stata` [here](https://www.stata.com/links/video-tutorials/), [here](https://data.princeton.edu/stata/), and [here](https://stats.idre.ucla.edu/stata/modules/). You can also likely use your search engine of choice to find even more, and perhaps better, materials for learning `Stata`. Although I will be teaching you all a lot about `Stata`, I find that students who do additional training often do much better in courses like this. This is in part because people have different learning styles, and there are many ways to go about doing work in `Stata`. This just means that my way may not always be the best way for you. Please keep this in mind as you explore the additional resources.

Why are we using `Stata` and not something else like `SPSS` or `R`? There are several answers, but the simplest is that `Stata` is an econometric software package that was designed to the types of analyses most commonly employed by political scientists and public administrators. Usage of `SPSS` has declined while many folks are also moving to the open source statistical environment `R`---myself included for many applications. But when it comes to classic econometrics `Stata` remains quite difficult to beat. `Stata` is also more accessible than `R` when it comes to learning many of these tools quickly. Having said that, my own preferences are trending towards `R` for most applications---espescially data vizualization via the `ggplot2` and broader `tidyverse` packages. If there is interest, we can spend some time learning these tools as well. 

## Technology

You will need to use your A-State email and have access to Blackboard. Otherwise assignments may be deployed via Dropbox or my website. If there is any issue with these items you should me know by the second week seminar at the latest. 

## Weekly Problem Sets in `Stata`

Each week, even on exam weeks, we will have a series of homework questions from the text. This are graded with partial credit, but no effort will result in a lower grade. We will also have relatively short assignments to complete using `Stata`. These are graded on a good faith effort basis, and as long as a clear/reasonable attempt was made you should receive full credit. Students having issues using `Stata` will need to schedule time with the Professor in order to make sure they understand where they are struggling and how to improve. Students that fail to do this will likely experience difficulty with the take-home portion of the exams (see below), which are graded on merit. Incomplete efforts on the problem sets will be downgraded accordingly and any missed assignments will receive a zero. __All assignments requiring a document submission must be submitted as PDF files__. Note that MS Office is free for A-State students and you can easily use it to create a PDF file by using File>Save As and the selecting PDF. More details will be provided on this early in the course. __All assignments that require document submission must have filenames that follow this convention: `your last name_assignment#.file extension`.__ As an example for myself and assignment one, I would do the following:  `wimpy_assignment1.pdf`. Failure to follow this convention will be met first with a warning, second with ten points off, and finally a zero after the third time. All assignments are due via email to Dr. Wimpy on the Sunday before class at 11:59 p.m.^[Note that you can also use the various implementations of `Stata` Markdown to make PDFs. Ask Dr. Wimpy if you are interested.] 

## Exams

There will be two exams. Note that the second exam will be comprehensive. The exams will consist of various question formats and the final will feature a "take home" portion using `Stata`. The "take-home" portion of the final exam will test your abilities to use `Stata`, conduct analyses, and explain results through clear writing. We will discuss the specifics of each exam as needed.

# Course Policies

The course policies that follow are subject to change, but assume they are in effect unless you hear otherwise from Dr. Wimpy.

## COVID-19 Pandemic

This is very much a fluid situation that could change quickly from one class meeting to the next. Given our relatively small room size and larger classroom size we will plan to meet in person each week per university guidelines. If conditions change, we will alter our course meeting place, delivery format, and materials as needed. Further information on the pandemic, and the university response, can be found here: <https://www.astate.edu/safety/novel-coronavirus/return-to-learn/>.

## Grading Policy

Your grade will consist of your performance on your participation in class, exam performance, and your ability to complete and submit the weekly assignments. The breakdown will be as follows:

## E-mail Policy

When e-mailing, please put POSC 6013: "Your Subject Here" in the subject field. Please also use proper openings and closings to the email. Grammatically correct and polite e-mails relieve much better responses than the alternatives.

### E-mail and Help Policy Regarding `Stata`

If you have an issue with writing code in `Stata`---and most people do---please do the following:

1. Search for the issue/error online. There are many resources and a vibrant online community for `Stata`.
2. Ask a classmate for help. You can work together on both assignments and the take-home portion of the exams. After all, this is how we work in the real world. Be sure to make the work your own, however, and verbatim copying will be at least questioned by Dr. Wimpy.
3. Post a question on the course Slack.
4. E-mail the Graduate Assistant (if applicable).
5. E-mail the Professor.

With respect to the last three options, you MUST provide a basic working example in order to expect a response. If you say: "hey, my `Stata` don't work", I will expect everyone to ignore you. On the other hand, for example, if you get an error when you enter:

into the `Stata` command line, then you should expect to get helpful feedback from one of us in the order provided. Along these same lines, classmates with the time and wherewithal to provide assistance to their colleagues will be highly appreciated by everyone in the course---including Dr. Wimpy and any Graduate Assistants.^[You get this error as the command is either `reg` or `regress`—in both cases the commands are lower case.]

### Make-Up Exam Policy

There are no make-ups for missed exams unless there is a valid excuse. Don't bother asking.

## Academic Dishonesty Policy

Plagiarism (the act of taking and/or using the ideas, work, and/or writings of another person as one’s own) is a serious offense against academic integrity which could result in failure for the paper or assignment, failure for the course, and/or expulsion from Arkansas State University.

Cheating is an act of dishonesty with the intention of obtaining and/or using information in a fraudulent manner. For further information, including specifics about what constitutes plagiarism or cheating, see A-State’s Academic Integrity Policy in the student [handbook](https://www.astate.edu/a/student-conduct/student-standards/handbook-home.dot).

## Disabilities Policy

Any student in this course who has a disability that may prevents full participation in this course should contact [Disability Services](https://www.astate.edu/disability/) (870-972-3964) as soon as possible so we can make the necessary accommodations to facilitate your educational opportunity.

## Copyright & Fair Use Statement

The materials used in this course are subject to copyright laws. For those materials which neither I nor A-State owns the copyright, I have either obtained a license for use or am using the materials in a manner that I reasonably believe is in compliance with the Fair Use exception to the copyright laws. The other materials used in this course are copyrighted. By this, I mean all materials generated for this class, which include but are not limited to syllabi, exams, lectures, quizzes, assignments, and any other document I post in Blackboard. Because these items are copyrighted, you do not have the right to copy and distribute any course materials unless I, or the document publishers, expressly grant permission.

